# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSwitch < Formula
  desc "Wrapper that drives multiple Claude CLI sessions remotely over WebSocket."
  homepage "https://github.com/jleal52/claude-switch"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.4/claude-switch_0.3.4_darwin_amd64.tar.gz"
      sha256 "fc69141933545a00ec838e4ca81aefe788cbf36ee769c1ed57027d460a4f68a5"

      define_method(:install) do
        bin.install "claude-switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.4/claude-switch_0.3.4_darwin_arm64.tar.gz"
      sha256 "b455d5f408872c7b1f0a4324beb45fcdaaa8ac1c49eb287680d0fc3d19104b9c"

      define_method(:install) do
        bin.install "claude-switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.4/claude-switch_0.3.4_linux_amd64.tar.gz"
      sha256 "2b16ff873cd95b6fd1be97ddd278a2ff05692ec308e22a781b487e33150c2a68"
      define_method(:install) do
        bin.install "claude-switch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.4/claude-switch_0.3.4_linux_arm64.tar.gz"
      sha256 "ed27ee4a28251e0672f45523c536f7e480ff07a9fc5c96ae022b1f68bbc8d279"
      define_method(:install) do
        bin.install "claude-switch"
      end
    end
  end

  service do
    run [opt_bin/"claude-switch"]
    keep_alive true
    working_dir Dir.home
    log_path var/"log/claude-switch.log"
    error_log_path var/"log/claude-switch.log"
    environment_variables PATH: "#{Dir.home}/.local/bin:#{std_service_path_env}"
  end

  test do
    output = shell_output("#{bin}/claude-switch pair 2>&1", 2)
    assert_match "pair requires a server base URL", output
  end
end
