# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSwitch < Formula
  desc "Wrapper that drives multiple Claude CLI sessions remotely over WebSocket."
  homepage "https://github.com/jleal52/claude-switch"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.4.0/claude-switch_0.4.0_darwin_amd64.tar.gz"
      sha256 "d7636afb0393c028bbd3ca83e45e51220657fcfe243cab04f22bc42e26bd2ac6"

      define_method(:install) do
        bin.install "claude-switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.4.0/claude-switch_0.4.0_darwin_arm64.tar.gz"
      sha256 "1268d57ad7f3d0cc15d1de9444514d6066b4f409695fb1220f01d4a09b954e76"

      define_method(:install) do
        bin.install "claude-switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.4.0/claude-switch_0.4.0_linux_amd64.tar.gz"
      sha256 "b826d7249f1aeb6c5ab6930dec47122afba3e13a8c82575870c0893ddfd0110a"
      define_method(:install) do
        bin.install "claude-switch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.4.0/claude-switch_0.4.0_linux_arm64.tar.gz"
      sha256 "721f331cdcce4e5ae51dfc0e050c3b5092a41d163b2fb6a1c180a2061af2212e"
      define_method(:install) do
        bin.install "claude-switch"
      end
    end
  end

  service do
    run [opt_bin/"claude-switch"]
    keep_alive true
    working_dir Dir.home
    log_path var/"log/claude-switch.log"
    error_log_path var/"log/claude-switch.log"
    environment_variables PATH: "#{Dir.home}/.local/bin:#{std_service_path_env}"
  end

  test do
    output = shell_output("#{bin}/claude-switch pair 2>&1", 2)
    assert_match "pair requires a server base URL", output
  end
end
