# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSwitch < Formula
  desc "Wrapper that drives multiple Claude CLI sessions remotely over WebSocket."
  homepage "https://github.com/jleal52/claude-switch"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.1/claude-switch_0.3.1_darwin_amd64.tar.gz"
      sha256 "85f8be0aa9feee141eebc8dfc5680be12c374dd785534ceef9e95560432adcf6"

      define_method(:install) do
        bin.install "claude-switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.1/claude-switch_0.3.1_darwin_arm64.tar.gz"
      sha256 "409562426ec1e3c71b7fbe045871b43d6c49a8b01afa0cdc6e6e94d01dd3b5b3"

      define_method(:install) do
        bin.install "claude-switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.1/claude-switch_0.3.1_linux_amd64.tar.gz"
      sha256 "a3c0393ceebc79306d6ccab1178b7109296708e5425621d4b5eef076fdd0fad5"
      define_method(:install) do
        bin.install "claude-switch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jleal52/claude-switch/releases/download/v0.3.1/claude-switch_0.3.1_linux_arm64.tar.gz"
      sha256 "d48540c8dd265c0588f8437f2bd1ed9eafd62b0d743b9e4597a46bcc05174be3"
      define_method(:install) do
        bin.install "claude-switch"
      end
    end
  end

  test do
    output = shell_output("#{bin}/claude-switch pair 2>&1", 2)
    assert_match "pair requires a server base URL", output
  end
end
